### ISSUE TITLE
multiple aggregations

### ISSUE THREAD

**Issue by heyanger** [heyanger/sqltools#20]
sql1 = select count(*) from highschooler
sql2 = select grade, count(*) from highschooler group by grade
wrongsql= select count(*), grade, count(*) from highschooler group by grade

**Comment by LuxuriaP** [comment]
When I run this, I get the following sql:
SELECT count(*), grade FROM highschooler group by grade
which is almost equal to the target sql. Do we still have to fix it?

**Comment by heyanger** [comment]
I guess its fine then, ill close thie
